treolabs/treocore

- application/Treo/Resources/i18n/de_DE/ModuleManager.json
- application/Treo/Resources/i18n/de_DE/Store.json
- application/Treo/Resources/i18n/en_US/ModuleManager.json
- application/Treo/Resources/i18n/en_US/Store.json
- application/Treo/Resources/layouts/Store/list.json
- application/Treo/Resources/metadata/entityDefs/Store.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/module-manager/list.tpl
- client/modules/treo-core/src/views/module-manager/list.js
- client/modules/treo-core/src/views/module-manager/record/row-actions/store.js
store entityDefs, translates, list layout;
templates, css;
> available modules to store as entity;

- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/src/views/site/navbar.js
> navigation menu fix;

- application/Treo/Resources/metadata/fields/wysiwyg.json
- client/modules/treo-core/src/views/fields/wysiwyg.js
> add wysiwyg show more text functional;

- application/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/admin/field-manager/fields/options.js
- client/modules/treo-core/src/views/fields/array.js
BUG #76554 fix backslash escaping err in data-value=
> BUG #76554 fix backslash escaping err in data-value=

- client/modules/treo-core/css/treo/treo-dark-theme.css
- html/installation.html
-i've added  centering of the logo on the installation page ... 
-used css and html:
-edited files: 
/var/www/treocore/client/modules/treo-core/css/treo/treo-dark-theme.css
and 
/var/www/treocore/html/installation.html
> t-75586 i've centred logo use css and html..

- client/modules/treo-core/src/views/record/list.js
fix dropdown error while field type data`s popup showing
> Error while opening popup of date type field

- app/Treo/Services/TreoStore.php
> Issue #473

- app/Treo/Services/Installer.php
> Issue #475

- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/src/views/fields/multi-enum.js
Css for import configurator;
Fixed selectize dropdown position for multi-enum
> Css for import configurator, fixed selectize dropdown position

- app/Treo/Composer/PostUpdate.php
- app/Treo/Console/ComposerLog.php
- app/Treo/Resources/i18n/de_DE/Composer.json
- app/Treo/Resources/i18n/en_US/Composer.json
Send notification about update modules.  Remove send notification with ComposerLog
https://github.com/treolabs/treocore/issues/479
> Update Send notification

- app/Treo/Listeners/Entity.php
- app/Treo/Resources/metadata/workflow/QueueItem.json
> Workflow init states

- app/Treo/Listeners/Metadata.php
- app/Treo/Resources/layouts/Settings/settings.json
Deleted old code Activities And Tasks
> Refactoring

- app/Treo/Composer/PostUpdate.php
- app/Treo/Resources/i18n/de_DE/Composer.json
- app/Treo/Resources/i18n/en_US/Composer.json
https://github.com/treolabs/treocore/issues/486
> Changes in the Notifications pop-up

- client/modules/treo-core/src/views/record/panels/relationship.js
Added data for unrelate event trigger in relationship panel
> Added data for unrelate event trigger in relationship panel

- client/modules/treo-core/css/treo/treo-dark-theme.css
Styles for collapsing buttons in Overview panel
> Styles for collapsing buttons in Overview panel

- app/Espo/Services/Record.php
- app/Treo/Core/Exceptions/NoChange.php
> Update entity only if input data is different from stored data

- client/modules/treo-core/src/views/record/detail.js
Added "expandLocales" param for multilang fields while filtering
> Added "expandLocales" param for multilang fields while filtering

- app/Treo/Composer/PostUpdate.php
- app/Treo/Resources/i18n/de_DE/Composer.json
- app/Treo/Resources/i18n/en_US/Composer.json
> fixed notifications

- client/modules/treo-core/src/views/login.js
Fix bug
https://github.com/treolabs/treocore/issues/450
> Unfilled fields notifications prior to the user login

- app/Treo/Resources/metadata/fields/image.json
Fixed actualFields param for image type field
> Fixed actualFields param for image type field

- app/Espo/Services/Record.php
- app/Treo/Listeners/Entity.php
Method SetOwner moved to Espo\Services\Record::setOwnerUser
https://github.com/treolabs/treocore/issues/490
> Set Owner for Entity in Controller

- app/Espo/Services/Record.php
https://github.com/treolabs/treocore/issues/505
> When editing a field of type linkMultiple returns "No changes for updating"

- app/Treo/Resources/layouts/Settings/settings.json
Moved row calendarEntityList with Core to Crm module
#521
> Moved row calendarEntityList with Core to Crm module

- app/Espo/Services/Record.php
* in isEntityUpdated function check if exists related entity
> checked if linked entity exists while check is entity update

- client/modules/treo-core/css/treo/treo-dark-theme.css
Styles for attributes panel in Product
> Styles for attributes panel in Product

- client/modules/treo-core/css/treo/treo-dark-theme.css
Fixed styles for attributes panel
> Fixed styles for attributes panel

- app/Treo/Core/Utils/Condition/Condition.php
Added condition NOT to DynamicLogic
> Added condition NOT to DynamicLogic

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/admin/layouts/list-small.js
Added checking for layoutListSmallDisabled param
> Added checking for layoutListSmallDisabled param

- app/Treo/Core/Utils/Condition/Condition.php
Fix bug in dynamicLogic-methods: checkEquals, checkLessThan
> Fix bug in dynamicLogic-methods: checkEquals, checkLessThan

- client/modules/treo-core/src/views/record/list.js
New dragNdrop mechanism for list
> New dragNdrop mechanism for list

- client/modules/treo-core/src/views/record/list.js
Added trigger for collection fetch after listSorted
> Added trigger for collection fetch after listSorted

- client/modules/treo-core/css/treo/treo-dark-theme.css
> Styles for dragNdrop panels

- client/modules/treo-core/src/views/fields/base.js
Added changing container for not visible element in showValidationMessage
> Added changing container for not visible element in showValidationMessage

- client/modules/treo-core/src/views/fields/base.js
- client/modules/treo-core/src/views/record/detail-bottom.js
Changed mechanic for showing popups while field validation
Added listener for collapsing panel
> Added listener for collapsing panel; changed mechanic for showing popups while field validation

- client/modules/treo-core/src/views/record/list.js
Fixed draggable list in locked panel
> Fixed draggable list in locked panel

- client/modules/treo-core/src/views/record/list.js
Backward compatibility for dragNdrop list
> Backward compatibility for dragNdrop list

- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/stream/notes/update.tpl
- client/modules/treo-core/src/views/stream/notes/update.js
> Fixed icon in header

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/admin/auth-log-record/list.js
- client/modules/treo-core/src/views/admin/auth-token/list.js
- client/modules/treo-core/src/views/admin/job/list.js
- client/modules/treo-core/src/views/admin/layouts/index.js
> Fixed icons in headers

- app/Espo/Services/Record.php
Added check for "hasCompleteness" for field validation
https://github.com/treolabs/treocore/issues/620
> Added check for "hasCompleteness" for field validation

- app/Espo/Resources/metadata/clientDefs/EmailAccount.json
- app/Espo/Resources/metadata/clientDefs/InboundEmail.json
- app/Espo/Resources/metadata/entityDefs/EmailAccount.json
- app/Espo/Resources/metadata/entityDefs/InboundEmail.json
Fixed validation Personal Email Accounts and Group Email Accounts
> Fixed validation Personal Email Accounts and Group Email Accounts

- app/Treo/Resources/i18n/de_DE/Global.json
- app/Treo/Resources/i18n/en_US/Global.json
- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/record/detail-small.tpl
- client/modules/treo-core/res/templates/record/edit-small.tpl
- client/modules/treo-core/res/templates/record/panels/default-side.tpl
- client/modules/treo-core/res/templates/record/panels/side.tpl
- client/modules/treo-core/src/views/record/detail-small.js
- client/modules/treo-core/src/views/record/panels/side.js
Modified detail-small & edit-small popup views
> Modified detail-small & edit-small popup views

- client/modules/treo-core/src/views/queue-manager/actions/download.js
Changed how to open download link
> Changed how to open download link

- app/Espo/Services/Record.php
Fixed bug in validation for required fields
> Fixed bug in validation for required fields

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/record/detail.tpl
- client/modules/treo-core/res/templates/record/edit.tpl
- client/modules/treo-core/src/search-manager.js
- client/modules/treo-core/src/views/record/detail.js
- client/modules/treo-core/src/views/record/edit.js
- client/modules/treo-core/src/views/record/list.js
- client/modules/treo-core/src/views/record/search.js
- client/modules/treo-core/src/views/site/navbar.js
> Modified detail page, styles

- app/Treo/Resources/i18n/de_DE/FieldManager.json
- app/Treo/Resources/i18n/en_US/FieldManager.json
Translates for unit field type
> Translates for unit field type

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/stream/panel.js
- client/modules/treo-core/src/views/stream/record/edit.js
Fixed bug with focus on textarea
> Fixed bug with focus on textarea

- app/Treo/Core/FileStorage/Storages/UploadDir.php
- client/modules/treo-core/src/views/record/list.js
Fixed draggable list params and move old files to new dirs
> Fixed draggable list params and move old files to new dirs

- app/Espo/Services/Record.php
- app/Treo/Resources/metadata/app/fileStorage.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
Changed settings fileStorage. Fixed bug for required fields
> Changed settings fileStorage. Fixed bug for required fields

- app/Espo/Services/Record.php
Fixed 'ChannelsIds' validation error is required
> Fixed 'ChannelsIds' validation error is required

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/admin/entity-manager/index.tpl
- client/modules/treo-core/res/templates/admin/integrations/index.tpl
- client/modules/treo-core/res/templates/admin/label-manager/index.tpl
- client/modules/treo-core/res/templates/admin/layouts/index.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/authentication.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/currency.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/inbound-emails.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/notifications.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/outbound-emails.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/representation-settings.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/settings.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/unit.tpl
- client/modules/treo-core/res/templates/admin/settings/headers/user-interface.tpl
- client/modules/treo-core/src/controllers/admin.js
- client/modules/treo-core/src/controllers/currency.js
- client/modules/treo-core/src/controllers/representation-settings.js
- client/modules/treo-core/src/views/admin/auth-token/list.js
- client/modules/treo-core/src/views/admin/entity-manager/index.js
- client/modules/treo-core/src/views/admin/integrations/index.js
- client/modules/treo-core/src/views/admin/label-manager/index.js
- client/modules/treo-core/src/views/composer/list.js
- client/modules/treo-core/src/views/preferences/edit.js
77437
Added displaying of subsection in the header of the administration section
Issue #602
> Added displaying of subsection in the header of the administration section

- client/modules/treo-core/css/treo/treo-dark-theme.css
75586
Fixed displaying of logo in installation menu
Issue #598
> Fixed displaying of logo in installation menu

- client/modules/treo-core/src/views/record/detail.js
76879
Fixed an issue when "edit mode" was shut off after incorrect save
> Fixed an issue when "edit mode" was shut off after incorrect save

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/res/templates/admin/field-manager/index.tpl
- client/modules/treo-core/res/templates/admin/link-manager/index.tpl
- client/modules/treo-core/src/views/admin/field-manager/index.js
- client/modules/treo-core/src/views/admin/link-manager/index.js
77437
Added subsection for Entity Manager (Fields, Relationships) and Jobs
Issue #458
> Added subsection for Entity Manager (Fields, Relationships) and Jobs

- app/Treo/Resources/i18n/de_DE/Global.json
- app/Treo/Resources/i18n/en_US/Global.json
- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/edit.js
- client/modules/treo-core/src/views/modals/edit.js
77435
Modified displaying of Entity creation windows/pop-ups title
Issue #457
> Modified displaying of Entity creation windows/pop-ups title

- client/modules/treo-core/css/treo/treo-dark-theme.css
> Styles for completeness

- client/modules/treo-core/src/views/fields/array.js
Fixed null values for multi-enum field type
> Fixed null values for multi-enum field type

- client/modules/treo-core/src/views/record/list.js
Added record check with shift for list
> Added record check with shift for list

- app/Treo/Migrations/V3Dot25Dot4.php
Changed engine in the table Attachment
> Changed engine in the table Attachment

- app/Espo/Core/Portal/Utils/ThemeManager.php
- app/Espo/Core/Utils/ThemeManager.php
- app/Espo/ORM/Repositories/RDB.php
- app/Treo/Core/Loaders/ThemeManager.php
- client/modules/treo-core/css/treo/treo-classic-theme.css
Added the ability to use theme with preferences
> Added the ability to use theme with preferences

- app/Espo/Core/ORM/Repositories/RDB.php
Added option skipProcessFileFieldsSave when storing an entity
https://github.com/treolabs/treocore/issues/692
> Added option skipProcessFileFieldsSave when storing an entity

- app/Espo/Core/Portal/Utils/ThemeManager.php
- app/Espo/Core/Utils/ThemeManager.php
- app/Treo/Core/Loaders/ThemeManager.php
> Fixed load theme

- client/modules/treo-core/src/search-manager.js
78442
Fixed writing isAttribute property for product attributes
From TreoPIM #194
> Fixed writing isAttribute property for product attributes

- app/Espo/Core/ORM/Repositories/RDB.php
- app/Espo/Resources/metadata/entityDefs/Settings.json
> Base currency is read only

- client/modules/treo-core/src/views/admin/field-manager/fields/options.js
81230
Fixed display of field keys
> Fixed display of field keys

- client/modules/treo-core/src/search-manager.js
Added isAttribute property record for DateTime attribute
From PIM https://github.com/treolabs/treopim/issues/194
> Added isAttribute property record for DateTime attribute

- app/Treo/Entities/Attachment.php
Change method _getStorage in the attachment entity file.
> fix _getStoreage in attachment entity

- app/Espo/Resources/i18n/en_US/Admin.json
- app/Treo/Resources/i18n/de_DE/Global.json
- app/Treo/Resources/i18n/en_US/Global.json
- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/src/views/fields/enum.js
81341
Added empty default value for enum
Fixed english translation of "Scheduled Jobs"
> Added empty default value for enum

- client/modules/treo-core/src/views/fields/enum.js
Fixed empty value;
Added param for disabling empty option
> Fixed empty value; added param for disabling empty option

- docs/en/user-guide/export-core.md
- docs/en/user-guide/import-core.md
> "Import/Export Feeds" modules are mentioned in the corresponding articles

- client/html/installation.html
- client/modules/treo-core/install/install.js
81463 
Added message for translation download error
Fixed issue with popover components
> Added message for translation download error

- client/modules/treo-core/src/views/fields/enum.js
81500 
Fixed issue with enum fields on duplication of product
> Fixed issue with enum fields on duplication of product

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/src/views/admin/layouts/grid.js
80232
Added ellipsis when text overflow
Added white background for draggable items
> Fixes for draggable elements

- client/modules/treo-core/src/views/admin/layouts/base.js
80379 
Added reload after saving layout
> Added reload after saving layout

- app/Treo/Resources/metadata/app/clientClassReplaceMap.json
- app/Treo/Resources/metadata/scopes/QueueItem.json
- app/Treo/Resources/metadata/scopes/TreoStore.json
- client/modules/treo-core/src/views/settings/fields/quick-create-list.js
79604
Added quickCreateListDisabled param for entity filter in quick create list
> Added quickCreateListDisabled param for entity filter in quick create list

- app/Treo/Resources/metadata/clientDefs/QueueItem.json
- client/modules/treo-core/res/templates/queue-manager/fields/name/detail.tpl
- client/modules/treo-core/src/views/queue-manager/detail.js
80388 
Fixed displaying of tags on queue-manager header and name label
> Fixed displaying of tags in queue-manager header and name label

- client/modules/treo-core/css/treo/treo-dark-theme.css
- client/modules/treo-core/res/templates/record/search.tpl
- client/modules/treo-core/src/views/record/search.js
80868 
Corrected right padding
Now length of the search field in modal dialog will be the entire available width
> Now length of the search field in modal dialog will be the entire available width

- client/modules/treo-core/css/treo/treo-dark-theme.css
80303
Added line limiter for product-variants attribute values
> Added line limiter for product-variants attribute values
